FROM dalibo/buildpack:rockylinux8

RUN set -ex; \
    yum -q -y install \
        cyrus-sasl-md5 \
        cyrus-sasl-devel \
        gcc \
        openldap-clients \
        openldap-devel \
        python3-virtualenv \
    ; \
    yum clean all ; \
    :

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PIP_NO_PYTHON_VERSION_WARNING 1

RUN set -ex; \
    curl -sSL https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3.6 - --ignore-installed ; \
    pip3.6 --version; \
    rm -rf ~/.cache/; \
    :

# See https://github.com/sdispater/poetry/issues/721
RUN set -ex; \
    curl -sSL https://install.python-poetry.org | python3.6 - --force --yes --version 1.1.13; \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry; \
    poetry --version; \
    :
